name: action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 21

      - name: Run build
        working-directory: app
        run: ./gradlew clean build

      - name: Run tests
        working-directory: app
        run: ./gradlew test

      - name: Run checkStyle
        working-directory: app
        run: ./gradlew checkStyleMain