name: action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 21

      - name: Run installDist
        working-directory: app
        run: ./gradlew installDist

      - name: Run tests
        working-directory: app
        run: ./gradlew test

      - name: Run checkStyle
        working-directory: app
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          workingDirectory: app
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco